spring.application.name=Paper Trading

spring.config.import=optional:file:.env[.properties]

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.datasource.url=${spring.datasource.url}
spring.datasource.username=${spring.datasource.username}
spring.datasource.password=${spring.datasource.password}
spring.jpa.properties.hibernate.jdbc.ssl_mode=require

spring.data.redis.host=${spring.data.redis.host}
spring.data.redis.port=${spring.data.redis.port}

jwt.secret=${jwt.secret}
jwt.expiration=${jwt.expiration}

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never


