spring.application.name=Paper Trading

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.jdbc.ssl_mode=require

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/paper_trading}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:22}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

jwt.secret=${JWT_SECRET:applebananaguavalichimangograpesorangeskiwifruits}
jwt.expiration=${JWT_EXPIRATION:604800000}

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never