spring.application.name=Paper Trading

spring.datasource.url=jdbc:mysql://localhost:3306/paper_trading
spring.datasource.username=root
spring.datasource.password=Sarabjeet@22

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never

stock.api.key=3ab714aaa2e44411a9210e33ee3db681
stock.api.url=https://api.twelvedata.com/price